add a command to edit existing worklogs
szymonkozak/tempomat pull request #46
Opened 2020-12-17 19:39 UTC by Vivec1990

This should resolve #45 
The workaround to changing the associated issue is to delete the existing worklog and create a new one with the given configuration.

2020-12-17 21:48 UTC, szymonkozak reviewed
Thanks for the contribution! :)

Could you also add tests for this feature? 

Also, please run `npm run lint` (this fixes some lint issues and shows you also errors that you have to fix manually).

2020-12-17 21:48 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +    async updateWorklog(worklogIdInput: string, input: UpdateWorklogInput) {
First, you should call `await checkToken()` to check if token is properly set. See the other methods in this scope.

2020-12-17 21:48 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +        } else {
This is not transactional. What if a worklog removal was done successfully but adding a new worklog failed (for example a new issue key is not found)? Then we just have removed worklog, not updated.

I am curious how it's implemented in Jira UI 🤔 
Maybe it would be safer to firstly add a new worklog and make deletion after successful adding? I am not sure, think about it, current behavior isn't acceptable unfortunately IMO.

2020-12-17 21:48 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +        const issue = await aliases.getIssueKey(issueKey) ?? issueKey
IMO `issueKey` should be named `issueKeyOrAlias`, and `issue` should be named `issueKey`.

2020-12-17 21:48 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +        const referenceDate = parseWhenArg(time.now(), input.when ? input.when : currentWorklog.startDate);
```input.when ? input.when : currentWorklog.startDate```
 can be replaced with 
```input.when ?? currentWorklog.startDate```

2020-12-17 21:48 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +        const issueKey = input.issueKeyOrAlias ? input.issueKeyOrAlias : currentWorklog.issue.key;
As above, I would use `??` here.

2020-12-17 21:48 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +            remainingEstimateSeconds: remainingEstimateSeconds(referenceDate, input.remainingEstimate)
Why we don't use `remaining estimate` from current worklog?

2020-12-17 21:48 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +            description: input.description ? input.description : currentWorklog.description,
As above (using `??`)

2020-12-17 21:48 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +        let parseResult = undefined
We don't need to declare variable as undefined explicitly.

2020-12-17 21:52 UTC, szymonkozak requested changes
Comments above.

2020-12-18 08:06 UTC, Vivec1990 commented on src/worklogs/worklogs.ts
> +            remainingEstimateSeconds: remainingEstimateSeconds(referenceDate, input.remainingEstimate)
Setting the remaining estimate seems to be optional, which would mean not setting it results in it not being changed.
But it could be done explicitly to make it clearer, i'll see how it behaves now.

2020-12-18 08:08 UTC, Vivec1990 commented on src/worklogs/worklogs.ts
> +        } else {
You are right.
If we add the new worklog first and there is an error, this should cancel, i'll check how this behaves by default.
If after adding the new worklog the deletion fails for some reason, it shouldn't matter too much, just need to inform the user.

2020-12-18 08:10 UTC, Vivec1990 commented on src/tempo.ts
> +            cli.action.stop('Done.')
Indeed it should, it seems like I forgot to add it.
Would the message be as in the addWorklog method, to include how to delete the, possibly changed, worklog?

2020-12-18 11:34 UTC, MiSikora requested changes
I left some nitpick formatting issues.

But this code needs to be covered with some acceptance tests. Scenarios that come to my mind.

1. Worklog parameters can be explicitly overridden.
1. Worklog parameters are not implicitly overriden.
1. Missing worklog parameters can be set.  
1. Not deleting worklog if it failed to be updated.
1. Deleting worklog if it updated succesfully.

If you wish to add unit tests for some of the code it is also cool but I don't think it is necessary.

2020-12-18 11:34 UTC, MiSikora commented on src/api/api.ts
> +        const body = { ...request, authorAccountId: credentials.accountId}
```suggestion
        const body = { ...request, authorAccountId: credentials.accountId }
```

2020-12-18 11:34 UTC, MiSikora commented on src/commands/edit.ts
> +        help: flags.help({char: 'h'}),
```suggestion
        help: flags.help( {char: 'h' }),
```

2020-12-18 11:34 UTC, MiSikora commented on src/commands/edit.ts
> +        const {args, flags} = this.parse(Edit)
```suggestion
        const { args, flags } = this.parse(Edit)
```

2020-12-18 11:34 UTC, MiSikora commented on src/worklogs/worklogs.ts
> +        if(input.issueKeyOrAlias) {
```suggestion
        if (input.issueKeyOrAlias) {
```

2020-12-18 11:34 UTC, MiSikora commented on src/worklogs/worklogs.ts
> +        if(input.durationOrInterval) {
```suggestion
        if (input.durationOrInterval) {
```

2020-12-18 11:52 UTC, szymonkozak commented
@MiSikora Formatting issues can be fixed automatically with running `npm run lint`.

2020-12-18 11:54 UTC, szymonkozak commented on src/tempo.ts
> +            cli.action.stop('Done.')
> Would the message be as in the addWorklog method, to include how to delete the, possibly changed, worklog?

Yes.

2020-12-18 12:06 UTC, szymonkozak commented on src/worklogs/worklogs.ts
> +            remainingEstimateSeconds: remainingEstimateSeconds(referenceDate, input.remainingEstimate)
> Setting the remaining estimate seems to be optional, which would mean not setting it results in it not being changed.

But technically if the `issueKey` was changed, we will create a completely new worklog, so we have to move all things from the old to the new one, including optional parameters.   

Correct me if I am wrong.

2021-05-30 22:27 UTC, szymonkozak commented
@Vivec1990 Are you going to finish implementing this or should I close this PR?

2021-06-07 21:49 UTC, szymonkozak commented
I am closing this due to a lack of activity.

2021-06-07 21:49 UTC, closed without merging